### ISSUE TITLE
MagicDraw should be labeled cross-platform

### ISSUE THREAD

**Issue by klotz84** [bpmnmatrix/bpmnmatrix.github.io#1]
Hi,

My name is David and I am with No Magic, I noticed that our product MagicDraw was not labeled as functional for Unix which is incorrect. Even though we are not browser based we are a cross platform software and run on Windows, IOS, Linux and Unix. I ask that you label MagicDraw as both cross-platform and Unix capable.

Thank you,

**Comment by dialogik** [comment]
Hi klotz84,

thank you for your Feedback. I have updated the `data.json` file accordingly (see 9af088f).

For the public: Information about MagicDraw OS platforms can be found here: http://www.nomagic.com/support/installation-and-use/teamwork-server-install.html.

Kind regards!
