### ISSUE TITLE
Yaoqiang

### ISSUE THREAD

**Issue by theelectricsoul** [bpmnmatrix/bpmnmatrix.github.io#16]
I was testing the design features of Yaoqiang the last three weeks. Looks pretty good and gets updated almost instantaneous as soon as you find a bug :)

So please update the "Latest release" column :)

**Comment by dialogik** [comment]
Can you provide any kind of proof that there has been a recent update?

**Comment by theelectricsoul** [comment]
Well the proof would be the link on your website. Yaoqiang is hosted on sourceforge.net
https://sourceforge.net/projects/bpmn/files/?source=navbar

**Comment by theelectricsoul** [comment]
Same applies to the camunda modeler :)
https://camunda.org/download/

**Comment by dialogik** [comment]
Thanks for your contribution, I have updated the latest release date.

**Comment by theelectricsoul** [comment]
Hmmm   you speak in past tense. But Yaoqiang hasn't been updated yet :)

**Comment by theelectricsoul** [comment]
https://sourceforge.net/projects/bpmn/?source=navbar
You only changed camunda it seems.

**Comment by dialogik** [comment]
You're right. Please consider handing in contributions as pull requests directly.
