### ISSUE TITLE
IBM Process Designer only runs on Windows

### ISSUE THREAD

**Issue by rlakatos** [bpmnmatrix/bpmnmatrix.github.io#18]
IBM Process Designer only runs on Windows, it is not cross platform.

The first sentence on this page says so.

[https://www.ibm.com/support/knowledgecenter/SSFTN5_8.5.7/com.ibm.wbpm.imuc.doc/topics/tins_bpm_pcntr_wle.html](https://www.ibm.com/support/knowledgecenter/SSFTN5_8.5.7/com.ibm.wbpm.imuc.doc/topics/tins_bpm_pcntr_wle.html)

**Comment by dialogik** [comment]
Thank you for your information, will update that.
