### ISSUE TITLE
Imixs-Workflow

### ISSUE THREAD

**Issue by rsoika** [bpmnmatrix/bpmnmatrix.github.io#19]
I would like to suggest [Imixs-Workflow](http://www.imixs.org). 

Here is the JSON object:

` {
        "Name": "Imixs-Workflow",
        "Version": "4.1.0",
        "URL": "http:\/\/www.imixs.org",
        "Creator": "Imixs",
        "Platform\/OS": "Cross-platform",
        "OS": {
            "Cross-Platform": true,
            "Windows": true,
            "Mac": true,
            "Linux": true,
            "Unix": true
        },
        "BPMN Version": "BPMN 2.0",
        "First Release": "2006",
        "Latest Release": "2017",
        "License": {
            "free": true,
            "proprietary": false,
            "Shareware": false,
            "Open Source": true
        }
    }`

**Comment by dialogik** [comment]
Thank you, we apreciate your contribution.
