### ISSUE TITLE
Add the BPMN Modeler for Confluence to the matrix

### ISSUE THREAD

**Issue by veltinshoss** [bpmnmatrix/bpmnmatrix.github.io#24]
Please add our BPMN designer "BPMN Modeler for Confluence" to the matrix. BPMN Modeler for Confluence is a BPMN 2.0 rendering toolkit and web modeler.

Our Website: www.viadee.de
 {
        "Name": "BPMN Modeler (for Confluence)",
        "Version": "1.0.8",
        "URL": "http:\/\/marketplace.atlassian.com\/plugins\/de.viadee.confluence.bpmn-plugin\/server\/overview",
        "Creator": "viadee IT-Unternehmensberatung GmbH",
        "Platform\/OS": "Cross-platform",
        "OS": {
            "Cross-Platform": true,
            "Windows": true,
            "Mac": false,
            "Linux": false,
            "Unix": false
        },
        "BPMN Version": "BPMN 2.0",
        "First Release": "2016-01",
        "Latest Release": "2017-07",
        "License": {
            "free": true,
            "proprietary": false,
            "Shareware": false,
            "Open Source": false
        }
    }
	
Thank you!

**Comment by dialogik** [comment]
Thanks for your contribution to the matrix. One question: You mark that this tool is cross-platform but you have different information for Windows, Mac, Linux and Unix. Shouldn't it be `true` for all platforms then?

**Comment by veltinshoss** [comment]
Good question ;-). The BPMN Modeler plugin depends on Atlassian confluence.
confluence supports all given platforms:
"Cross-Platform": true,
"Windows": true,
"Mac": true,
"Linux": true,
"Unix": true

**Comment by veltinshoss** [comment]
Do you need futher information to add the BPMN Modeler Plugin?

**Comment by dialogik** [comment]
No, I will add it the next time I edit the data file, together with the other hand ins. If you need it quicker please hand it in as pull request; I will merge immediately.
