### ISSUE TITLE
Updated needed for Logizian and Visual Paradigm

### ISSUE THREAD

**Issue by johnlikeforever** [bpmnmatrix/bpmnmatrix.github.io#32]
First of all thank you for creating this great site! I found the information about Logizian and Visual Paradigm outdated and would like to suggest the changes below:

1. The product Logizian was discontinued since the product amalgamation in Visual Paradigm version 11.1, so the entire row should be removed.

2. For Visual Paradigm:
2.1 It should be labelled Cross Platform, and with all Windows, Linux, Mac and Unix highlighted. 
2.2 The latest release date should be 2017/09/14, which is currently unfilled
2.3 The URL of link is updated to:
https://www.visual-paradigm.com/features/bpmn-diagram-and-tools/

I hope you will consider the changes above. I am not sure if I can / should provide any evidence for the points above. Please let me know if this is needed. Thank you for your attention.

**Comment by moritzhesse** [comment]
I have checkd your change requests and it's okay like that. Thanks a lot for your updates!
