### ISSUE TITLE
bpmn.io is not Open Source

### ISSUE THREAD

**Issue by Whisprin** [bpmnmatrix/bpmnmatrix.github.io#39]
bpmn.io is released under the terms of the bpmn.io license which is not an open source license.
Its repository can be found here: https://github.com/bpmn-io/bpmn-js

The license here: https://bpmn.io/license/ and https://github.com/bpmn-io/bpmn-js/blob/master/LICENSE

**Comment by Whisprin** [comment]
Additionally, the Modeler is released under the MIT license but depends on bpmn-js and other libraries which are released under proprietary licenses.

**Comment by dialogik** [comment]
Thank you very much for you analysis and your pull request. I'm fine with labeling it under a proprietary license. But I want to keep it under the _Open Source_ label since I go with Richard Stallmans definition of open source

> "OSS is software for which the source code is freely and publicly available, though the specific licensing agreements vary as to what one is allowed to do with that code." ([Richard Stallman](https://www.gnu.org/philosophy/open-source-misses-the-point.html.en))

**Comment by Whisprin** [comment]
Hm, if you don't agree with the legal definition of open source, shouldn't you refrain from using the term?

> This is why we do not agree with open source, and do not use that term. ([GNU](https://www.gnu.org/philosophy/open-source-misses-the-point.html.en))

Maybe "Free Software" and "Source Available" would be better labels then. However, in terms of software licenses (as opposed to software in general) "open source" has a specific meaning.
