### ISSUE TITLE
Add bpmn.io

### ISSUE THREAD

**Issue by NastiJohn** [bpmnmatrix/bpmnmatrix.github.io#4]
Please ass our project bpmn.io to the matrix. bpmn.io is a BPMN 2.0 rendering toolkit and web modeler.

Here's some more information:

Website: http://bpmn.io/
Github: https://github.com/bpmn-io/bpmn-js
Name: bpmn.io
Creator: Camunda Services GmbH
OS: Cross-Platform
Platform/OS: Web
BPMN Version: BPMN 2.0
First Release: Feb 2014
Latest Release: Apr 2015
Software License: free

**Comment by dialogik** [comment]
Thank you for your contribution.
