### ISSUE TITLE
Creately BPM Software

### ISSUE THREAD

**Issue by shehan-cinergix** [bpmnmatrix/bpmnmatrix.github.io#50]
You can also Creately BPM Software to the list.

Link: [https://creately.com/lp/bpm-software-online/](https://creately.com/lp/bpm-software-online/)

**Comment by moritzhesse** [comment]
Thank you for your contribution! Could you please help by filling out the "New application" template?

**Name:** 
**Version:** (Application Version)
**URL:** (Full URL)
**Creator:** (Company/Author)

## Platform/OS

**Platform/OS:** (Describe supported OSs)
**Cross-Platform:** yes/no
**Windows:** yes/no
**Mac:** yes/no
**Linux:** yes/no
**Unix:** yes/no

## Versions/Releases

**BPMN Version:** 
**First Release:** (Date)
**Latest Release:** (Date)

## Licensing

**License free:** yes/no
**Proprietary:** yes/no
**Shareware:** yes/no
**Open Source:** yes/no

**Comment by shehan-cinergix** [comment]
Hi! Thank you for your reply. Below are the details you have requested.

Name: BPM Software
Version: version 7.0.14
URL: https://creately.com/lp/bpm-software-online/
Creator: Creately

Platform/OS
Platform/OS: Cloud based app which can be used on Windows, Mac OSX and Linux platforms 
Cross-Platform: yes
Windows: yes
Mac: yes
Linux: yes
Unix: no

Versions/Releases N/A
BPMN Version: N/A
First Release: 2008
Latest Release: 01st March 2021

Licensing
License free: no
Proprietary: yes
Shareware: no
Open Source: no

**Comment by moritzhesse** [comment]
Great, thank you. I have added BPM Software.
