### ISSUE TITLE
Changes Company and product Names

### ISSUE THREAD

**Issue by GBTECAG** [bpmnmatrix/bpmnmatrix.github.io#52]
Hello, 

We are listed on your homepage, but our company and our product now have a new name. 
Company name: GBTEC Software AG
product name: BIC Platform

and we have a free version of the software early on

Thanks and best regards,
Marina Meinelt
GBTEC Software AG

marina.meinelt@gbtec.de

**Comment by moritzhesse** [comment]
I have changed the data for BIC Platform. Thank you for your update.

**Comment by GBTECAG** [comment]
Thank you!

Von: Moritz Hesse <notifications@github.com>
Gesendet: Dienstag, 9. März 2021 12:43
An: bpmnmatrix/bpmnmatrix.github.io <bpmnmatrix.github.io@noreply.github.com>
Cc: Meinelt, Marina <marina.meinelt@gbtec.de>; Author <author@noreply.github.com>
Betreff: Re: [bpmnmatrix/bpmnmatrix.github.io] Changes Company and product Names (#52)


I have changed the data for BIC Platform. Thank you for your update.
