### ISSUE TITLE
XML Frames Template

### ISSUE THREAD

**Issue by Mat-Hac** [bpmnmatrix/bpmnmatrix.github.io#54]
{
        "Name": "XML Frames",
        "Version": "",
        "URL": "https:\/\/xmlframes.com\/",
        "Creator": "Matthieu Giroux",
        "Platform\/OS": "Client/Server",
        "OS": {
            "Cross-Platform": true,
            "Windows": true,
            "Mac": it was,
            "Linux": true,
            "Unix": it can be
        },
        "BPMN Version": "Depends on W4 BPMN+",
        "First Release": "2009",
        "Latest Release": "2021",
        "License": {
            "free": true,
            "proprietary": false,
            "Shareware": false,
            "Open Source": true
        }
    }

**Comment by moritzhesse** [comment]
Thank you for your contribution. I modified the URL (`https` does not work...) and set `Mac` and `Unix` to false since the script can only handle `true`/`false`.
