### ISSUE TITLE
Latest release dates seem to be out of date

### ISSUE THREAD

**Issue by russoz** [bpmnmatrix/bpmnmatrix.github.io#59]
Hi,

First and foremost, thanks for compiling the list and putting them nicely into this table. It is really helpful!

However, I could not help noticing that many of the "Latest release" dates seem to be outdated. Camunda Modeler, for example, had a release 4 days ago, the page says the last one was in 2016. I imagine it must quite a hassle to keep tabs on all these different players, so I would suggest removing that column altogether, as the data quality there is bound to be low. 

Just my 2 cents.

Cheers,
AZ

**Comment by dialogik** [comment]
Hey @russoz, yes I do not (and don't plan to do in the future) check the data in this project all the time so the older the data the more likely it is that the data is not up-to-date anymore.

Feel free to perform your own research and update the information provided by editing the data in [`data.json`](https://github.com/bpmnmatrix/bpmnmatrix.github.io/blob/master/data.json) and submitting your changes by a pull request.

Thank you and kind regards!
