### ISSUE TITLE
Camunda is open source

### ISSUE THREAD

**Issue by leolux** [bpmnmatrix/bpmnmatrix.github.io#6]
the source can be found here: https://github.com/camunda

**Comment by dialogik** [comment]
Thank you for your contribution. The link you provided is just the page of the github user @camunda. Could you provide the link to source of the Camunda Modeler?

**Comment by leolux** [comment]
Camunda is platform and is built out of many projects. The link I provided gives you access to all the source code including the modeler: https://github.com/camunda/camunda-modeler

**Comment by dialogik** [comment]
Great, thanks!
