### ISSUE TITLE
Update AuraPortal

### ISSUE THREAD

**Issue by kirstyroberts** [bpmnmatrix/bpmnmatrix.github.io#7]
Please can you update the latest release date for AuraPortal 
It should be 2016
Many Thanks

**Comment by dialogik** [comment]
Do you have any kind of verification? I've [looked it up](http://www.auraportal.com/en/download-bpm) but couldn't find any hint on the release date.

**Comment by kirstyroberts** [comment]
Thank you for getting back to me. 

 

After downloading the modeler from www.auraportal.com, you can select 'Help' then 'About' and the date of the latest version appears (see attached image)

 

Kind regards,

 

Kirsty Roberts

Translator and Marketing Specialist

 

Skype: Gap_kirsty.roberts

E: kirsty.roberts@auraportal.com

 

cid:image002.png@01D09D4D.B9574010

Gartner: AuraPortal iBPMS positioned as "Visionary" in Gartner's "Magic Quadrant for iBPMS 2015".

**Comment by dialogik** [comment]
I cannot see any attachment but your word (as Aura employee) is sufficient. I've updated the entry. Thank you for your contribution.
